# Generated by Django 4.2 on 2023-05-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
