# Generated by Django 4.2 on 2023-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_starting_bid_listing_bid_listing_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
