# Generated by Django 4.2 on 2023-05-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_current_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='price',
        ),
    ]
