# Generated by Django 4.2 on 2023-05-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_bid_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='bid',
        ),
    ]
