# Generated by Django 4.2 on 2023-05-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_bid_remove_listing_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bids',
            new_name='bid',
        ),
    ]
