# Generated by Django 4.2 on 2023-05-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_bids_listing_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='price',
        ),
    ]
