# Generated by Django 4.2 on 2023-05-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_rename_bid_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
