# Generated by Django 4.2 on 2023-05-18 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listing_bids_remove_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='current_bidder',
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
