# Generated by Django 4.2 on 2023-05-18 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_rename_listing_bid_listing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidder',
        ),
    ]
