# Generated by Django 4.2 on 2023-05-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_rename_user_bid_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
