# Generated by Django 4.2 on 2023-05-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_rename_listing_id_bid_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
