# Generated by Django 4.2 on 2023-05-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_rename_comment_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
